from fpdf import FPDF
from datetime import datetime
import unicodedata


def clean(text: str) -> str:
    """
    Remove or replace characters that latin-1 / core PDF fonts cannot handle.
    Replaces smart quotes, em-dashes, ellipsis etc. with ASCII equivalents.
    """
    replacements = {
        '\u2014': '-',   # em dash
        '\u2013': '-',   # en dash
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u201c': '"',   # left double quote
        '\u201d': '"',   # right double quote
        '\u2026': '...', # ellipsis
        '\u00a0': ' ',   # non-breaking space
        '\u2022': '-',   # bullet
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Strip anything still outside latin-1
    return text.encode('latin-1', errors='ignore').decode('latin-1')


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(26, 58, 143)
        self.cell(0, 10, "ContradictAI - Contradiction Detection Report",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(26, 58, 143)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by ContradictAI", align="C")


def severity_color(severity: str):
    return {
        "High":   (229, 57,  53),
        "Medium": (251, 140,  0),
        "Low":    (253, 216, 53),
    }.get(severity, (100, 100, 100))


def generate_pdf_report(
    filename: str,
    doc_name: str,
    total_sections: int,
    contradictions: list,
    clean_count: int
) -> bytes:
    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Meta
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, clean(f"Document : {doc_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Summary box
    pdf.set_fill_color(240, 244, 255)
    pdf.set_draw_color(26, 58, 143)
    pdf.rect(10, pdf.get_y(), 190, 28, style="FD")
    pdf.set_xy(14, pdf.get_y() + 4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(26, 58, 143)
    pdf.cell(63, 7, f"Total Sections: {total_sections}")
    pdf.cell(63, 7, f"Contradictions: {len(contradictions)}")
    pdf.cell(63, 7, f"Clean Sections: {clean_count}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(14, pdf.get_y() + 4)

    high = sum(1 for c in contradictions if c.get("severity") == "High")
    med  = sum(1 for c in contradictions if c.get("severity") == "Medium")
    low  = sum(1 for c in contradictions if c.get("severity") == "Low")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(229, 57, 53);  pdf.cell(63, 7, f"High: {high}")
    pdf.set_text_color(251, 140, 0);  pdf.cell(63, 7, f"Medium: {med}")
    pdf.set_text_color(100, 150, 50); pdf.cell(63, 7, f"Low: {low}")
    pdf.ln(18)

    if not contradictions:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(67, 160, 71)
        pdf.cell(0, 10, "No contradictions detected. Document is internally consistent.",
                 new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    # Contradiction entries
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(26, 58, 143)
    pdf.cell(0, 8, "Detected Contradictions", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    for i, c in enumerate(contradictions):
        sev  = c.get("severity", "Low")
        conf = c.get("confidence", 0)
        ctype = c.get("type", "Direct")
        r, g, b = severity_color(sev)

        # Header bar
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.rect(10, pdf.get_y(), 190, 8, style="F")
        pdf.set_xy(12, pdf.get_y() + 1)
        header_text = clean(f"#{i+1}  {c['target']}  |  {sev} Severity  |  {ctype}  |  Confidence: {conf}%")
        pdf.cell(0, 6, header_text, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        # Target text preview
        pdf.set_text_color(60, 60, 60)
        pdf.set_font("Helvetica", "I", 9)
        preview = clean(c.get("target_text", "")[:300].replace('\n', ' '))
        if len(c.get("target_text", "")) > 300:
            preview += "..."
        pdf.set_x(12)
        pdf.multi_cell(186, 5, f"Section text: {preview}")
        pdf.ln(1)

        # Analysis
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        analysis_clean = clean(c.get("analysis", "").replace('\n', ' ').strip())
        pdf.set_x(12)
        pdf.multi_cell(186, 5, analysis_clean)
        pdf.ln(3)

        # Compared against
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.set_x(12)
        compared = clean(f"Compared against: {', '.join(c.get('related_sections', []))}")
        pdf.cell(0, 5, compared, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    return bytes(pdf.output())